### PR TITLE
Fix some of Bugs in CTE, include subquery cost, tabel reference

### PR DESCRIPTION
**Pull request by 9DemonFox**

### CODE REVIEW

**Comment by zhouqingqing** [comment]
please describe bugs you fixed

**Comment by 9DemonFox** [comment]
image

simplefy the plan of cte subquery.

**Comment by 9DemonFox** [comment]
image-20201125112620123

mutiple times refer to cte

**Comment by 9DemonFox** [comment]
image-20201125112540303

cte filter push down

**Comment by zhouqingqing** [comment]
There are two general ways to CTEs processing: (1) treat CTE as a blackbox subquery; (2) inline and expand CTE as subquery. Are you supporting both?

**Comment by 9DemonFox** [comment]
Before:
image
Now:
image

cte tabel reference. consider:
```
 sql = "with cte as (select a_common2.a1 from a a_common2 where a1 = 1) select a_common.a1 from a a_common where a_common.a1 in (select a1 from cte)";
```
this case is refering to tpcds q95
```
with ws_wh as
(select ws1.ws_order_number,ws1.ws_warehouse_sk wh1,ws2.ws_warehouse_sk wh2
 from web_sales ws1,web_sales ws2
 where ws1.ws_order_number = ws2.ws_order_number
   and ws1.ws_warehouse_sk <> ws2.ws_warehouse_sk)
 select  
   count(distinct ws_order_number) as "order count"
  ,sum(ws_ext_ship_cost) as "total shipping cost"
  ,sum(ws_net_profit) as "total net profit"
from
   web_sales ws1
  ,date_dim
  ,customer_address
  ,web_site
where
    d_date between date '2001-4-01' and
           (cast('2001-4-01' as date) + 60 days)
and ws1.ws_ship_date_sk = d_date_sk
and ws1.ws_ship_addr_sk = ca_address_sk
and ca_state = 'VA'
and ws1.ws_web_site_sk = web_site_sk
and web_company_name = 'pri'
and ws1.ws_order_number in (select ws_order_number
                            from ws_wh)
and ws1.ws_order_number in (select wr_order_number
                            from web_returns,ws_wh
                            where wr_order_number = ws_wh.ws_order_number)
order by count(distinct ws_order_number)
limit 100
```

**Review by 9DemonFox — COMMENTED** [review]
> There are two general ways to CTEs processing: (1) treat CTE as a blackbox subquery; (2) inline and expand CTE as subquery. Are you supporting both?
> 
> I would suggest you split the PR into two parts: (1) generate TPCDS plan as it is without any fix; (2) fix TPCDS queries.

yes , both supported.
but that PR is not merged. So i delete it several minutes ago.

**Pull request closed without merging**
